name: firebase_picture_uploader
description: Picture upload widget which helps selecting and uploading one or multiple images to firebase storage.
version: 1.3.2
homepage: https://github.com/Rodiii/flutter_firebase_picture_uploader
maintainer: Christoph Rothermel (@rothech)

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.11.0"

dependencies:
  flutter:
    sdk: flutter
    
  cached_network_image: ^3.3.1
  firebase_storage: ^11.2.5
  firebase_core: ^2.15.0
  image: ^4.1.4
  image_picker: ^1.1.2
  image_cropper: ^8.0.2
  shared_preferences: ^2.0.15
  path_provider: ^2.0.11
  cupertino_icons: ^1.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
 